apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: test-app
  namespace: default
  selfLink: /api/v1/namespaces/default/services/test-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
