apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: demo
  namespace: default
  selfLink: /api/v1/namespaces/default/services/demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
